### ISSUE TITLE
Warning File.exists?

### ISSUE THREAD

**Issue by rubyFeedback** [michaelfairley/hasu#4]
.gem/gems/hasu-0.1.6/lib/hasu.rb:34: warning: File.exists? is a deprecated name, use File.exist? instead

A harmless warning, but if you ever get around to update hasu, perhaps you could also
update the code there. Hope I am not nitpicky! Sorry, kind regards - I found the hasu
project indirectly via a tic-tac-toe game by the way.

**Comment by michaelfairley** [comment]
Thanks! Just pushed a new version that fixes this.
